/**
 * ISO 3166-1 alpha-2 → GOV.UK foreign-travel-advice slug, generated from
 * https://www.gov.uk/api/content/foreign-travel-advice (Sep 2026). Territories
 * covered by another country's page map to that page (e.g. PR → usa).
 * The UK itself (GB) has no FCDO advice page.
 */
export const FCDO_SLUGS: Readonly<Record<string, string>> = {
  AC: "st-helena-ascension-and-tristan-da-cunha", AD: "andorra", AE: "united-arab-emirates",
  AF: "afghanistan", AG: "antigua-and-barbuda", AI: "anguilla", AL: "albania", AM: "armenia",
  AO: "angola", AQ: "antarctica-british-antarctic-territory", AR: "argentina", AS: "usa",
  AT: "austria", AU: "australia", AW: "aruba", AZ: "azerbaijan", BA: "bosnia-and-herzegovina",
  BB: "barbados", BD: "bangladesh", BE: "belgium", BF: "burkina-faso", BG: "bulgaria",
  BH: "bahrain", BI: "burundi", BJ: "benin", BL: "st-martin-and-st-barthelemy", BM: "bermuda",
  BN: "brunei", BO: "bolivia", BQ: "bonaire-st-eustatius-saba", BR: "brazil", BS: "bahamas",
  BT: "bhutan", BW: "botswana", BY: "belarus", BZ: "belize", CA: "canada",
  CD: "democratic-republic-of-the-congo", CF: "central-african-republic", CG: "congo",
  CH: "switzerland", CI: "cote-d-ivoire", CK: "cook-islands-tokelau-and-niue", CL: "chile",
  CM: "cameroon", CN: "china", CO: "colombia", CR: "costa-rica", CU: "cuba", CV: "cape-verde",
  CW: "curacao", CX: "australia", CY: "cyprus", CZ: "czechia", DE: "germany", DJ: "djibouti",
  DK: "denmark", DM: "dominica", DO: "dominican-republic", DZ: "algeria", EC: "ecuador",
  EE: "estonia", EG: "egypt", EH: "western-sahara", ER: "eritrea", ES: "spain", ET: "ethiopia",
  FI: "finland", FJ: "fiji", FK: "falkland-islands", FM: "federated-states-of-micronesia",
  FO: "denmark", FR: "france", GA: "gabon", GD: "grenada", GE: "georgia", GF: "french-guiana",
  GH: "ghana", GI: "gibraltar", GL: "denmark", GM: "the-gambia", GN: "guinea", GP: "guadeloupe",
  GQ: "equatorial-guinea", GR: "greece", GS: "south-georgia-and-south-sandwich-islands",
  GT: "guatemala", GU: "usa", GW: "guinea-bissau", GY: "guyana", HK: "hong-kong", HN: "honduras",
  HR: "croatia", HT: "haiti", HU: "hungary", IC: "spain", ID: "indonesia", IE: "ireland",
  IL: "israel", IN: "india", IO: "british-indian-ocean-territory", IQ: "iraq", IR: "iran",
  IS: "iceland", IT: "italy", JM: "jamaica", JO: "jordan", JP: "japan", KE: "kenya",
  KG: "kyrgyzstan", KH: "cambodia", KI: "kiribati", KM: "comoros", KN: "st-kitts-and-nevis",
  KP: "north-korea", KR: "south-korea", KW: "kuwait", KY: "cayman-islands", KZ: "kazakhstan",
  LA: "laos", LB: "lebanon", LC: "st-lucia", LI: "liechtenstein", LK: "sri-lanka", LR: "liberia",
  LS: "lesotho", LT: "lithuania", LU: "luxembourg", LV: "latvia", LY: "libya", MA: "morocco",
  MC: "monaco", MD: "moldova", ME: "montenegro", MG: "madagascar", MH: "marshall-islands",
  MK: "north-macedonia", ML: "mali", MM: "myanmar", MN: "mongolia", MO: "macao", MQ: "martinique",
  MR: "mauritania", MS: "montserrat", MT: "malta", MU: "mauritius", MV: "maldives", MW: "malawi",
  MX: "mexico", MY: "malaysia", MZ: "mozambique", NA: "namibia", NC: "new-caledonia", NE: "niger",
  NG: "nigeria", NI: "nicaragua", NL: "netherlands", NO: "norway", NP: "nepal", NR: "nauru",
  NU: "cook-islands-tokelau-and-niue", NZ: "new-zealand", OM: "oman", PA: "panama", PE: "peru",
  PF: "french-polynesia", PG: "papua-new-guinea", PH: "philippines", PK: "pakistan", PL: "poland",
  PM: "st-pierre-and-miquelon", PN: "pitcairn-island", PR: "usa", PS: "palestine", PT: "portugal",
  PW: "palau", PY: "paraguay", QA: "qatar", RE: "reunion", RO: "romania", RS: "serbia",
  RU: "russia", RW: "rwanda", SA: "saudi-arabia", SB: "solomon-islands", SC: "seychelles",
  SD: "sudan", SE: "sweden", SG: "singapore", SH: "st-helena-ascension-and-tristan-da-cunha",
  SI: "slovenia", SK: "slovakia", SL: "sierra-leone", SM: "san-marino", SN: "senegal",
  SO: "somalia", SR: "suriname", SS: "south-sudan", ST: "sao-tome-and-principe", SV: "el-salvador",
  SX: "st-maarten", SY: "syria", SZ: "eswatini", TA: "st-helena-ascension-and-tristan-da-cunha",
  TC: "turks-and-caicos-islands", TD: "chad", TG: "togo", TH: "thailand", TJ: "tajikistan",
  TK: "cook-islands-tokelau-and-niue", TL: "timor-leste", TM: "turkmenistan", TN: "tunisia",
  TO: "tonga", TR: "turkey", TT: "trinidad-and-tobago", TV: "tuvalu", TW: "taiwan", TZ: "tanzania",
  UA: "ukraine", UG: "uganda", US: "usa", UY: "uruguay", UZ: "uzbekistan",
  VC: "st-vincent-and-the-grenadines", VE: "venezuela", VG: "british-virgin-islands", VI: "usa",
  VN: "vietnam", VU: "vanuatu", WF: "wallis-and-futuna", WS: "samoa", XK: "kosovo", YE: "yemen",
  YT: "mayotte", ZA: "south-africa", ZM: "zambia", ZW: "zimbabwe",
};
